[project]
name = "biomercs-ml"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "stLmpp", email = "gui.stlmpp@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "yt-dlp>=2026.8.19",
]

[project.scripts]
biomercs-ml = "biomercs_ml:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
